/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfilesSteamIdImport } from './routes/profiles/$steamId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfilesSteamIdRoute = ProfilesSteamIdImport.update({
  id: '/profiles/$steamId',
  path: '/profiles/$steamId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profiles/$steamId': {
      id: '/profiles/$steamId'
      path: '/profiles/$steamId'
      fullPath: '/profiles/$steamId'
      preLoaderRoute: typeof ProfilesSteamIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiles/$steamId': typeof ProfilesSteamIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles/$steamId': typeof ProfilesSteamIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profiles/$steamId': typeof ProfilesSteamIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profiles/$steamId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profiles/$steamId'
  id: '__root__' | '/' | '/profiles/$steamId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesSteamIdRoute: typeof ProfilesSteamIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesSteamIdRoute: ProfilesSteamIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profiles/$steamId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profiles/$steamId": {
      "filePath": "profiles/$steamId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
